### ISSUE TITLE
Unresolved reference: cpgLanguageCxx

### ISSUE THREAD

**Issue by morbitzer** [Fraunhofer-AISEC/cpg#1191]
Hi, 

when trying to build cpg-neo4j, I get the following error message:

```
 ../gradlew clean
Type-safe project accessors is an incubating feature.

> Configure project :
Java frontend is enabled
C/C++ frontend is disabled
Go frontend is disabled
Python frontend is disabled
LLVM frontend is enabled
TypeScript frontend is disabled

> Configure project :cpg-analysis
e: <cpg>/cpg-analysis/build.gradle.kts:46:33: Unresolved reference: cpgLanguageCxx

FAILURE: Build failed with an exception.

* Where:
Build file '<cpg>/cpg-analysis/build.gradle.kts' line: 46

* What went wrong:
Script compilation error:

  Line 46:     testImplementation(projects.cpgLanguageCxx)
                                           ^ Unresolved reference: cpgLanguageCxx

1 error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 815ms
12 actionable tasks: 12 up-to-date
```
git bisect tells me that it was commit 2b89676a6f6f4e8894e040b9a658ffa78735e614 that caused the problem.

**Comment by morbitzer** [comment]
Indeed, that fixed it. Thanks!
